MurvasBokhandel/Controllers/BorrowerAdminController.cs
using Common;
using Common.Model;
using Common.Share;
using Repository.EntityModel;
using Repository.Validation;
using Services.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace MurvasBokhandel.Controllers
{
    public class BorrowerAdminController : Controller
    {
        public ActionResult Start(string letter = "A")
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission() && LetterLists.LetterList.Contains(letter))
            {
                return View(new LettersAndBorrowers(LetterLists.LetterList, BorrowerService.GetBorrowersByLetter(letter))) ;
            }
            return Redirect("/Error/Code/403");
        }

        // Lägger till användarkonto till en borrower
        public ActionResult AddUser(user u)
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                BorrowerWithBorrows b = BorrowerService.GetBorrowerWithBorrows(u.PersonId);

                if (ModelState.IsValid)
                {
                    if (PasswordValidaton.IsValid(u.Password))
                    {
                        if (!UserService.EmailExists(u.Email))
                        {
                            AuthService.CreateUser(u);
                            TempData["Alert"] = AlertView.Build("Du har skapat ett användarkonto till låntagaren.", AlertType.Success);
                            return RedirectToAction("Borrower", new { id = u.PersonId });
                        }

                        TempData["Alert"] = AlertView.Build("Konto med emailen " + u.Email + " existerar. Ange en annan!", AlertType.Danger);

                        return View("Borrower", b);
                    }

                    TempData["Alert"] = AlertView.Build(PasswordValidaton.ErrorMessage, AlertType.Danger);

                    return RedirectToAction("Borrower", new { id = u.PersonId });
                }


                TempData["Alert"] = AlertView.BuildErrors(ViewData);

                return RedirectToAction("Borrower", new { id = u.PersonId });
            }

            return Redirect("/Error/Code/403");
        }

        [HttpGet]
        public ActionResult Borrower(string id)
        {
            Auth _auth = new Auth((BorrowerWithUser)Session["User"]);
            if (_auth.HasAdminPermission())
            {
                if (!BorrowerService.BorrowerExists(id))
                    return Redirect("/Error/Code/404");

                if (UserService.BorrowerIsUser(_auth.LoggedInUser, id))
                    return Redirect("/User/GetAcountInfo");

                return View(BorrowerService.GetBorrowerWithBorrows(id));
            }
            
            return Redirect("/Error/Code/403");
        }

        // Används för att uppdatera en borrower
        [HttpPost]
        public ActionResult Borrower(BorrowerWithUser BorrowerWithUser)
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                if (ModelState.IsValid && (BorrowerWithUser.Borrower.CategoryId == 1 ||
                                             BorrowerWithUser.Borrower.CategoryId == 2 ||
                                             BorrowerWithUser.Borrower.CategoryId == 3 ||
                                             BorrowerWithUser.Borrower.CategoryId == 4))
                {
                    user tempU = AuthService.GetUserByPersonId(BorrowerWithUser.Borrower.PersonId);

                    if (BorrowerWithUser.User != null && !(UserService.EmailExists(BorrowerWithUser.User.Email) && BorrowerWithUser.User.Email != tempU.Email))
                        UserService.Update(BorrowerWithUser, null);
                    else
                        BorrowerService.UpdateBorrower(BorrowerWithUser.Borrower);
                    
                    TempData["Alert"] = AlertView.Build("Du har uppdaterat låntagaren.", AlertType.Success);
                    return RedirectToAction("/Borrower/" + BorrowerWithUser.Borrower.PersonId);
                }
                return View(BorrowerService.GetBorrowerWithBorrows(BorrowerWithUser.Borrower.PersonId));
            }
            return Redirect("/Error/Code/403");
        }
     
        // Tar bort en borrower och konto om det finns
        public ActionResult Remove(BorrowerWithBorrows bwb)
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                if (!BorrowerService.RemoveBorrower(bwb.BorrowerWithUser.Borrower))
                {
                    TempData["Alert"] = AlertView.Build("Det gick inte att ta bort låntagare. Kontrollera att inga aktiva lån finns.", AlertType.Danger);

                    return RedirectToAction("Borrower", new { id = bwb.BorrowerWithUser.Borrower.PersonId });
                }

                TempData["Alert"] = AlertView.Build("Låntagare med PersonId "+bwb.BorrowerWithUser.Borrower.PersonId + " är nu borttagen", AlertType.Success);
                
                return Redirect("Start");
            }
            return Redirect("/Error/Code/403");
        }

        public ActionResult RenewLoan(string barcode, string personid, int index)
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                ActiveAndHistoryBorrows borrows = new ActiveAndHistoryBorrows();
                borrows.Active = BorrowService.GetActiveBorrowedBooks(personid);
                BorrowService.RenewLoad(BorrowerService.GetBorrower(personid), borrows.Active[index].Borrow.Barcode);

                TempData["AlertView"] = AlertView.Build("Lån är uppdaterade.", AlertType.Success);
           
                return Redirect("/BorrowerAdmin/Borrower/" + personid);
            }
            return Redirect("/Error/Code/403");
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                return View(new BorrowerAndCategories()
                {
                    Borrower = new borrower(),
                    Categories = CategoryService.GetCategories()
                });
            }
            return Redirect("/Error/Code/403");
        }

        // Sparar en ny borrower till databasen
        [HttpPost]
        public ActionResult Create(BorrowerAndCategories baci)
        {
            if (new Auth((BorrowerWithUser)Session["User"]).HasAdminPermission())
            {
                baci.Categories = CategoryService.GetCategories();

                if (ModelState.IsValid && (baci.CatergoryId == 1 || 
                                             baci.CatergoryId == 2 ||
                                             baci.CatergoryId == 3 ||
                                             baci.CatergoryId == 4))
                {
                    if (!BorrowerService.BorrowerExists(baci.Borrower.PersonId))
                    {

                        borrower b = new borrower();
                        b = baci.Borrower;
                        b.CategoryId = baci.CatergoryId;
                        BorrowerService.StoreBorrower(b);

                        TempData["Alert"] = AlertView.Build("Låntagare " + baci.Borrower.FirstName + " " + baci.Borrower.LastName + " skapad.", AlertType.Success);

                        return Redirect("Start");
                    }

                    baci.PushAlert(AlertView.Build("Detta personnumret är redan registrerat hos oss", AlertType.Danger));
                    return View(baci);
                }
                
                return View(baci);
            }

            return Redirect("/Error/Code/403");
        }
    }
}

MurvasBokhandel/Controllers/BorrowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services.Service;
using Common.Model;
using Repository.Repository;
using Repository.EntityModel;

namespace MurvasBokhandel.Controllers.Borrower
{
    public class BorrowerController : Controller
    {
        // GET: /Borrower/        
        static private List<BorrowedBookCopy> BBC = new List<BorrowedBookCopy>();

        public BorrowerController() {
            user u = (user)Session["User"];
            BBC = BorrowService.GetBorrowedBooks(u.PersonId);
        }

        public ActionResult Start() {
            return View(BBC);
        }

        public ActionResult ReloanAll() {
            foreach (BorrowedBookCopy b in BBC) {
                BorrowService.updateBorrowDate(b.borrow);
                BorrowService.updateToBeReturnedDate(b.borrow);
            }
            return RedirectToAction("Start", BBC);
        }

        public ActionResult Reloan(int index) {
            BorrowService.updateBorrowDate(BBC[index].borrow);
            BorrowService.updateToBeReturnedDate(BBC[index].borrow);
            return View("Start", BBC);
        }
	}
}

MurvasBokhandel/Views/BorrowerAdmin/Borrower.cshtml
@model Common.Model.BorrowerWithBorrows
@{
    ViewBag.Title = "Borrower";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            @Model.BorrowerWithUser.Borrower.FirstName @Model.BorrowerWithUser.Borrower.LastName - <small><a href="/BorrowerAdmin">Låntagare</a></small>
            @if (Model.BorrowerWithUser.User.Email != null) { 
                <font size="5" color="green" style="float:right"> Konto finns</font>
            }
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        @if (TempData["Alert"] != null)
        {
            @Html.Raw(TempData["Alert"])
        }
        @using (Html.BeginForm("Borrower", "BorrowerAdmin", new { @id = "borrower_form" }))
        {            
            @Html.HiddenFor(m => m.BorrowerWithUser.Borrower.PersonId)
            if (Model.BorrowerWithUser.User.Email != null)
            {
                <h4>Kontoinformation</h4>
                @Html.HiddenFor(m => m.BorrowerWithUser.User.PersonId)
                <div class="form-group">
                    <label>Email</label>
                    @Html.TextBoxFor(m => m.BorrowerWithUser.User.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BorrowerWithUser.User.Email, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label>Roll</label>
                    <select name="BorrowerWithUser.User.RoleId" class="form-control">
                        @{
                            foreach (var role in @Model.Roles)
                            {
                                <option value="@role.Id" @(Model.BorrowerWithUser.User.RoleId == role.Id ? "selected" : "")>@role.Name</option>
                            }
                        }
                        @Html.ValidationMessageFor(m => m.BorrowerWithUser.User.RoleId, "", new { @class = "text-danger" })
                    </select>
                </div>
            <hr />
            }
            <h4>Låntagarinformation</h4>
            <div class="form-group">
                <label>Personnummer</label>
                <input type="text" disabled class="form-control" value="@Model.BorrowerWithUser.Borrower.PersonId" />
                @Html.ValidationMessageFor(m => m.BorrowerWithUser.Borrower.PersonId, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Förnamn</label>
                @Html.TextBoxFor(m => m.BorrowerWithUser.Borrower.FirstName, new { @class = "form-control", placeholder = "Förnamn" })
                @Html.ValidationMessageFor(m => m.BorrowerWithUser.Borrower.FirstName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Efternamn</label>
                @Html.TextBoxFor(m => m.BorrowerWithUser.Borrower.LastName, new { @class = "form-control", placeholder = "Efternamn", data_parsley_required = "true" })
                @Html.ValidationMessageFor(m => m.BorrowerWithUser.Borrower.LastName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Adress</label>
                @Html.TextBoxFor(m => m.BorrowerWithUser.Borrower.Address, new { @class = "form-control", placeholder = "Adress", data_parsley_required = "true" })
                @Html.ValidationMessageFor(m => m.BorrowerWithUser.Borrower.Address, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Telefonnummer</label>
                @Html.TextBoxFor(m => m.BorrowerWithUser.Borrower.Telno, new { @class = "form-control", placeholder = "0000-000000", data_parsley_required = "true" })
                @Html.ValidationMessageFor(m => m.BorrowerWithUser.Borrower.Telno, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Kategori</label>
                @Html.DropDownListFor(m => m.BorrowerWithUser.Borrower.CategoryId, new SelectList(Model.Categories, "CatergoryId", "Category"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-warning" value="Uppdatera" />
                <button id="btnRemove" type="button" class="btn btn-danger pull-right" onclick="checkSure()">Ta bort</button>
            </div>
            <div class="form-group" style="float:right">
                <label id="lblSure" style="display: none; margin: 10px">Säker?</label>
                <button id="btnNo" type="submit" class="btn btn-danger pull-right" onclick="hide()" style="display: none; margin: 10px">Nej</button>
                <button id="btnYes" type="submit" class="btn btn-danger pull-right" form="form-remove-borrower" style="display: none; margin: 10px">Ja</button>
            </div>

        }

        @using (Html.BeginForm("Remove", "BorrowerAdmin", FormMethod.Post, new { @id = "form-remove-borrower" }))
        {
            @Html.HiddenFor(m => m.BorrowerWithUser.Borrower.PersonId)
        }
    </div>


@if (Model.BorrowerWithUser.User.Email == null)
{
    <div class="col-md-6 jumbotron" style="float:right" id="divAddUser">
        <h3>Skapa inloggning</h3>
        <form method="post" action="/BorrowerAdmin/AddUser" id="form-addusertoborrower">
            <input type="hidden" name="PersonId" class="form-control" value="@Model.BorrowerWithUser.Borrower.PersonId" />
            <div class="form-group">
                <label>Personnummer</label>
                <input type="text" class="form-control" value="@Model.BorrowerWithUser.Borrower.PersonId" disabled />
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="email" name="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label>Lösenord</label>
                <input type="password" name="Password" class="form-control" />
            </div>
            <div class="form-group">
                <label>Roll</label>
                <select name="RoleId" class="form-control">
                    @{
                        foreach (var role in @Model.Roles)
                        {
                            <option value="@role.Id">@role.Name</option>
                        }
                    }
                </select>
            </div>
            <button style="float:right" class="btn btn-primary" form="form-addusertoborrower">Spara</button>
        </form>
    </div>
}
</div>
<div class="row">
    <div class="col-md-12">
        <h4>Lånade böcker</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Titel</th>
                    <th>Författare</th>
                    <th>ISBN</th>
                    <th>Publicerad</th>
                    <th>Barcode</th>
                    <th>Lånad den</th>
                    <th>Förseningsavgift</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <h3>Aktuella</h3>
                <tbody>
                    @for (int i = 0; i < Model.Borrows.Active.Count; i++)
                    {
                        <form method="post" action="/BorrowerAdmin/RenewLoan/">
                            <input type="hidden" value="@i" name="index" />
                            <input type="hidden" value="@Model.Borrows.Active[i].Borrow.Barcode" name="barcode" />
                            <input type="hidden" value="@Model.Borrows.Active[i].Borrow.PersonId" name="personid" />
                            <tr>
                                <td>
                                    <a href="/Book/GetBook/?isbn=@Model.Borrows.Active[i].Book.ISBN">@Model.Borrows.Active[i].Book.Title</a>
                                </td>
                                <td>
                                    @for (int j = 0; j < Model.Borrows.Active[i].Authors.Count; j++)
                                    {
                                        <a href="/Author/GetAuthor/?aid=@Model.Borrows.Active[i].Authors[j].Aid">@Model.Borrows.Active[i].Authors[j].FirstName @Model.Borrows.Active[i].Authors[j].LastName,</a>
                                    }
                                </td>
                                <td>
                                    <a href="/Book/GetBook/?isbn=@Model.Borrows.Active[i].Book.ISBN">@Model.Borrows.Active[i].Book.ISBN</a>
                                </td>
                                <td>@Model.Borrows.Active[i].Book.PublicationYear</td>
                                <td>@Model.Borrows.Active[i].Borrow.Barcode</td>
                                <td>@Model.Borrows.Active[i].Borrow.BorrowDate</td>
                                <td>
                                    @Model.Borrows.Active[i].Fine:-
                                    <input name="reloan" value="Låna om" type="submit" style="float: right" class="btn btn-default" />
                                    @if (Model.Borrows.Active[i].Borrow.ToBeReturnedDate < DateTime.Today)
                                    {
                                        <font color="red" style="float:right">Försenad</font>
                                    }
                                </td>
                            </tr>
                        </form>
                    }
                </tbody>
        </table>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Titel</th>
                    <th>Författare</th>
                    <th>ISBN</th>
                    <th>Publicerad</th>
                    <th>Barcode</th>
                    <th>Lånad</th>
                    <th>Tillbaka lämnad</th>
                    <th></th>
                </tr>
            </thead>
            <h3>Historik</h3>
            <tbody>
                @for (int i = 0; i < Model.Borrows.History.Count; i++)
                {
                    <tr>
                        <td>
                            <a href="/Book/GetBook/?isbn=@Model.Borrows.History[i].Book.ISBN">@Model.Borrows.History[i].Book.Title</a>
                        </td>
                        <td>
                            @for (int j = 0; j < Model.Borrows.History[i].Authors.Count; j++)
                            {
                                <a href="/Author/GetAuthor/?aid=@Model.Borrows.History[i].Authors[j].Aid">@Model.Borrows.History[i].Authors[j].FirstName @Model.Borrows.History[i].Authors[j].LastName,</a>
                            }
                    </td>
                    <td>
                        <a href="/Book/GetBook/?isbn=@Model.Borrows.History[i].Book.ISBN">@Model.Borrows.History[i].Book.ISBN</a>
                    </td>
                    <td>@Model.Borrows.History[i].Book.PublicationYear</td>
                    <td>@Model.Borrows.History[i].Borrow.Barcode</td>
                    <td>@Model.Borrows.History[i].Borrow.BorrowDate</td>
                    <td>@Model.Borrows.History[i].Borrow.ReturnDate</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        function checkSure() {
            document.getElementById('btnRemove').disabled = 'true'
            document.getElementById('lblSure').style.display = 'block'
            document.getElementById('btnYes').style.display = 'block'
            document.getElementById('btnNo').style.display = 'block'
        }
        function hide() {
            document.getElementById('btnRemove').disabled = 'false'
            document.getElementById('lblSure').style.display = 'none'
            document.getElementById('btnYes').style.display = 'none'
            document.getElementById('btnNo').style.display = 'none'
        }
    </script>
}

MurvasBokhandel/Views/BorrowerAdmin/Create.cshtml
@model Common.Model.BorrowerAndCategories

@{
    ViewBag.Title = "Create";
}

<h2>Skapa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-8">

        @if (Model.IsAlerted())
        {
            @Html.Raw(Model.PopAlert())
        }

        <h4><a href="/BorrowerAdmin">Låntagare</a></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Personnummer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Borrower.PersonId, new { htmlAttributes = new { @class = "form-control", placeholder = "XXXXXXXX-XXXX", data_parsley_required = "true" } })
                @Html.ValidationMessageFor(model => model.Borrower.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Förnamn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Borrower.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Förnamn" } })
                @Html.ValidationMessageFor(model => model.Borrower.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Efternamn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Borrower.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Efternamn"} })
                @Html.ValidationMessageFor(model => model.Borrower.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Adress", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Borrower.Address, new { htmlAttributes = new { @class = "form-control", placeholder = "Adress" } })
                @Html.ValidationMessageFor(model => model.Borrower.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Telefonnummer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Borrower.Telno, new { htmlAttributes = new { @class = "form-control", placeholder = "0000-000000" } })
                @Html.ValidationMessageFor(model => model.Borrower.Telno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DropDownListFor(model => model.CatergoryId, new SelectList(Model.Categories, "CatergoryId", "Category"), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MurvasBokhandel/Views/BorrowerAdmin/Start.cshtml
@model Common.Model.LettersAndBorrowers
@{
    ViewBag.Title = "Start";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Låntagare <small><label class="label label-warning">Administratorläge</label></small>
            <a href="/BorrowerAdmin/Create" class="btn btn-default pull-right">Skapa ny låntagare</a>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        @if (TempData["Alert"] != null)
        {
            @Html.Raw(TempData["Alert"])
        }
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        @Html.Raw(Model.Render("/BorrowerAdmin/?letter=", "/BorrowerAdmin/Borrower/", "PersonId", new string[] {
            "LastName", "FirstName"
        }))
    </div>
</div>